server:
  context-path: /seller
  port: 8089

spring:
  profiles:
    active: prod
  datasource:
    username: hcon
    password: hconuser
    url: jdbc:mysql://101.37.35.73:3306/mall?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

logging:
  file: logs/spring-boot-logging.log
  level:
    com:
      scoprion:
        mall:
          wx:
            mapper: debug
          backstage:
            mapper: debug
mybatis:
  type-aliases-package: com.scopion.seller.domain
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
     cache-enabled: true
     mapUnderscoreToCamelCase: true
pagehelper:
  helper-dialect: mysql
  reasonable: false         #默认开启  true:页码小于1或者页码大于最大时返回 第一条或者最后一条
  support-methods-arguments: true
  params: count=countSql



